# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Mirror subpackage."""
