# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.dpo.trainer pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import torch
from g2c.nn import Module, resolve_device
from g2c.training import AdamW, clip_grad_norm_, cosine_with_warmup
from .data import PreferenceExample, pad_and_collate_pref
from .loss import dpo_loss, sequence_logprob

from g2c.dpo.trainer import DPOTrainer


class _DPOTrainerImpl:  # patched onto DPOTrainer by apply()
    def train_step(self) -> dict[str, float]:
        """Perform one DPO step on a fresh random batch.

        Returns:
            A dict of metrics for this step:
                'loss':            scalar loss (Python float)
                'lr':              lr applied this step (Python float)
                'grad_norm':       pre-clip global grad norm if
                                   grad_clip is set; else 0.0
                'chosen_reward':   mean implicit reward on chosen
                'rejected_reward': mean implicit reward on rejected
                'reward_margin':   mean(chosen - rejected) reward
                'accuracy':        fraction with chosen > rejected

        Recipe — same shape as Module 13's `SFTTrainer.train_step`,
        but with two-model bookkeeping:

            1. # Sample a fresh batch.
               (cx, cy, cm, rx, ry, rm) = self._sample_batch(self.examples)
               cx = cx.to(self.device)
               cy = cy.to(self.device)
               cm = cm.to(self.device)
               rx = rx.to(self.device)
               ry = ry.to(self.device)
               rm = rm.to(self.device)

            2. # LR for THIS step (before incrementing the counter).
               lr = self.lr()
               self.optimizer.lr = lr

            3. self.optimizer.zero_grad()

            4. # Policy forwards — WITH gradient.
               policy_chosen_logp   = self._logp_under(self.model, cx, cy, cm)
               policy_rejected_logp = self._logp_under(self.model, rx, ry, rm)

            5. # Reference forwards — NO gradient.
               with torch.no_grad():
                   ref_chosen_logp   = self._logp_under(self.ref_model, cx, cy, cm)
                   ref_rejected_logp = self._logp_under(self.ref_model, rx, ry, rm)

            6. loss, metrics = dpo_loss(
                   policy_chosen_logp,
                   policy_rejected_logp,
                   ref_chosen_logp,
                   ref_rejected_logp,
                   beta=self.beta,
               )

            7. loss.backward()

            8. # Optional global gradient clipping.
               if self.grad_clip is not None:
                   grad_norm = clip_grad_norm_(
                       self.model.parameters(), self.grad_clip
                   )
               else:
                   grad_norm = 0.0

            9. self.optimizer.step()

           10. self.step += 1

           11. return {
                   'loss':            loss.item(),
                   'lr':              lr,
                   'grad_norm':       grad_norm,
                   'chosen_reward':   metrics['chosen_reward'].item(),
                   'rejected_reward': metrics['rejected_reward'].item(),
                   'reward_margin':   metrics['reward_margin'].item(),
                   'accuracy':        metrics['accuracy'].item(),
               }

        Common reorderings to avoid (same as Modules 10/13):

          * Computing the reference forwards WITH gradient. The
            optimizer would not step them, because
            `optimizer.params` doesn't include them — so it's a
            silent waste of memory, not a correctness bug. Still:
            wrap the ref forwards in `torch.no_grad()` so the autograd
            graph doesn't grow through them.

          * Forgetting `optimizer.zero_grad()`. The .grad on
            `model.parameters()` accumulates across steps without it.

          * Clipping after `optimizer.step()`. The gradients have
            already been consumed; clipping after is a no-op.
        """
        (cx, cy, cm, rx, ry, rm) = self._sample_batch(self.examples)
        cx = cx.to(self.device)
        cy = cy.to(self.device)
        cm = cm.to(self.device)
        rx = rx.to(self.device)
        ry = ry.to(self.device)
        rm = rm.to(self.device)

        lr = self.lr()
        self.optimizer.lr = lr
        self.optimizer.zero_grad()

        policy_chosen_logp = self._logp_under(self.model, cx, cy, cm)
        policy_rejected_logp = self._logp_under(self.model, rx, ry, rm)

        with torch.no_grad():
            ref_chosen_logp = self._logp_under(self.ref_model, cx, cy, cm)
            ref_rejected_logp = self._logp_under(self.ref_model, rx, ry, rm)

        loss, metrics = dpo_loss(
            policy_chosen_logp,
            policy_rejected_logp,
            ref_chosen_logp,
            ref_rejected_logp,
            beta=self.beta,
        )

        loss.backward()

        if self.grad_clip is not None:
            grad_norm = clip_grad_norm_(
                self.model.parameters(), self.grad_clip
            )
        else:
            grad_norm = 0.0

        self.optimizer.step()
        self.step += 1

        return {
            "loss": loss.item(),
            "lr": lr,
            "grad_norm": grad_norm,
            "chosen_reward": metrics["chosen_reward"].item(),
            "rejected_reward": metrics["rejected_reward"].item(),
            "reward_margin": metrics["reward_margin"].item(),
            "accuracy": metrics["accuracy"].item(),
        }

