# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.sampling.generate pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import torch
from g2c.sampling.repetition_penalty import apply_repetition_penalty
from g2c.sampling.temperature import apply_temperature
from g2c.sampling.top_k import top_k_filter
from g2c.sampling.top_p import top_p_filter


@torch.no_grad()
def generate(
    model,
    prompt_ids: torch.Tensor,
    max_new_tokens: int,
    *,
    temperature: float = 1.0,
    top_k: int | None = None,
    top_p: float | None = None,
    repetition_penalty: float = 1.0,
    eos_id: int | None = None,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    """Autoregressively continue `prompt_ids` for up to `max_new_tokens`.

    Args:
        model: any module with a `forward(token_ids: (1, T))` that
            returns `(1, T, V)` logits. `TransformerLM` from Module 09
            is the prototype, but the loop is model-agnostic. The
            model is also expected to expose `max_seq_len: int` so
            generate can crop the context window.
        prompt_ids: 1-D LongTensor `(T_prompt,)`. Must be non-empty
            and at most `model.max_seq_len` tokens.
        max_new_tokens: how many new tokens to sample.
        temperature: softmax temperature. `1.0` is the model's native
            distribution; smaller values are sharper, larger flatter.
            `0.0` is the special "greedy" mode (argmax — deterministic).
        top_k: keep at most this many of the highest-probability
            tokens at each step. `None` disables top-k.
        top_p: keep tokens whose cumulative probability reaches this.
            `None` disables top-p.
        repetition_penalty: CTRL-style multiplicative penalty on
            tokens already present in the running sequence. `1.0` is
            no penalty. Typical values: `1.05`–`1.3`.
        eos_id: optional end-of-sequence token id. If provided,
            generation stops as soon as this token is sampled (it IS
            included in the output).
        generator: optional `torch.Generator` for reproducible
            sampling. Has no effect in greedy mode.

    Returns:
        1-D LongTensor of length at most `T_prompt + max_new_tokens`,
        equal to `prompt_ids` followed by the sampled continuation.
        Shorter if `eos_id` was emitted before `max_new_tokens`.

    Recipe:
        1. # Validation:
           if prompt_ids.dim() != 1 or prompt_ids.numel() == 0:
               raise ValueError(...)
           if temperature < 0:
               raise ValueError(...)

        2. # Decide once whether we're in greedy mode. Greedy
           # bypasses ALL warpers (the warpers are about reshaping a
           # sampled distribution; argmax doesn't sample).
           greedy = (temperature == 0.0)

        3. full_ids = prompt_ids.detach().cpu().clone()
           # Keep the running token IDs on CPU for easy decoding and
           # reproducible sampling. Move only the per-step context to
           # the model's device for the forward pass.
           device = getattr(model, "device", torch.device("cpu"))

        4. for _ in range(max_new_tokens):
               # 4a. Crop context to the model's positional capacity.
               ctx = full_ids[-model.max_seq_len:]
               ctx = ctx.to(device).unsqueeze(0)           # (1, T_ctx)

               # 4b. Forward pass; extract last position's logits.
               logits = model(ctx)                         # (1, T_ctx, V)
               last_logits = logits[:, -1, :].cpu()        # (1, V)

               if greedy:
                   # 4c-greedy. Argmax — no warpers, no sampling.
                   next_id = last_logits.argmax(dim=-1)    # (1,)
               else:
                   # 4c-sample. Warpers in canonical order.
                   if repetition_penalty != 1.0:
                       last_logits = apply_repetition_penalty(
                           last_logits, full_ids, repetition_penalty
                       )
                   last_logits = apply_temperature(last_logits, temperature)
                   if top_k is not None:
                       last_logits = top_k_filter(last_logits, top_k)
                   if top_p is not None:
                       last_logits = top_p_filter(last_logits, top_p)

                   probs = torch.softmax(last_logits, dim=-1)   # (1, V)
                   next_id = torch.multinomial(
                       probs, num_samples=1, generator=generator
                   ).squeeze(-1)                           # (1,)

               # 4d. Append the new token.
               full_ids = torch.cat([full_ids, next_id], dim=0)

               # 4e. Early stop on EOS.
               if eos_id is not None and next_id.item() == eos_id:
                   break

        5. return full_ids

    Notes:
      - The whole function is wrapped in `@torch.no_grad()` (see the
        decorator above the signature). Generation is inference; we
        don't need autograd, and skipping it saves both memory and
        compute.
      - The order of warpers — repetition → temperature → top-k →
        top-p — matches HuggingFace's `LogitsProcessorList` default.
        Reordering produces different distributions in non-trivial
        ways; if you're reproducing a paper's recipe, check what
        order it used.
      - This loop is `O(max_new_tokens × T_ctx²)` in attention compute
        because every step recomputes attention from scratch. KV
        caching makes it `O(max_new_tokens × T_ctx)`; we don't cache
        in this module — the lesson here is the loop, not the
        optimization.
    """
    if prompt_ids.dim() != 1 or prompt_ids.numel() == 0:
        raise ValueError(f'prompt_ids must be a non-empty 1-D tensor, got {prompt_ids}')
    if temperature < 0:
        raise ValueError(f'Temperature must be non-negative, got {temperature}')
    vocab_size = getattr(model, "vocab_size", None)
    if vocab_size is not None:
        min_id = int(prompt_ids.min().item())
        max_id = int(prompt_ids.max().item())
        if min_id < 0 or max_id >= vocab_size:
            raise ValueError(
                "prompt_ids contain token IDs outside the model vocab: "
                f"min={min_id}, max={max_id}, model.vocab_size={vocab_size}. "
                "Encode prompts with tokenizer.encode_with_vocab_size(..., "
                "model.vocab_size)."
            )
    
    greedy = (temperature == 0.0)
    full_ids = prompt_ids.detach().cpu().clone()
    device = getattr(model, "device", torch.device("cpu"))
    for _ in range(max_new_tokens):
        ctx = full_ids[-model.max_seq_len:].to(device).unsqueeze(0)
        logits = model(ctx)
        last_logits = logits[:, -1, :].cpu()

        if greedy:
            next_id = last_logits.argmax(dim=-1)
        else:
            if repetition_penalty != 1.0:
                last_logits = apply_repetition_penalty(
                    last_logits, full_ids, repetition_penalty
                )
            last_logits = apply_temperature(last_logits, temperature)
            if top_k is not None:
                last_logits = top_k_filter(last_logits, top_k)
            if top_p is not None:
                last_logits = top_p_filter(last_logits, top_p)

            probs = torch.softmax(last_logits, dim=-1)
            next_id = torch.multinomial(
                probs, num_samples=1, generator=generator
            ).squeeze(-1)

        full_ids = torch.cat([full_ids, next_id], dim=0)

        if eos_id is not None and next_id.item() == eos_id:
            break

    return full_ids
