# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.nn.optim pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

from collections.abc import Iterable
import torch

from g2c.nn.optim import SGD


class _SGDImpl:  # patched onto SGD by apply()
    def step(self) -> None:
        """Apply the SGD update to every parameter.

        Update rule (per parameter, using `.data` to bypass autograd tracking):
            delta = grad + weight_decay * param            # data, not graph
            param.data -= lr * delta

        Implementation hints:
            - Wrap the body in `with torch.no_grad():` so the update itself
              is not tracked by autograd. (Equivalent: operate on `.data`
              directly; cleaner: use `no_grad`.)
            - Skip parameters whose `.grad` is None (they didn't participate).
            - When weight_decay is 0, the term drops out — no need to special-case.
        """
        with torch.no_grad():
            for p in self.params:
                if p.grad is not None:
                    delta = p.grad + self.weight_decay * p
                    p -= self.lr * delta

