# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.tensors.broadcasting pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

from collections.abc import Iterable
from typing import Union
Number = Union[int, float]

from g2c.tensors.broadcasting import TinyArray


class _TinyArrayImpl:  # patched onto TinyArray by apply()
    def __add__(self, other: "TinyArray") -> "TinyArray":
        """Element-wise add with broadcasting.

        Steps:
            1. Compute `out_shape = broadcast_shapes(self.shape, other.shape)`.
            2. Allocate an output data list of the right total length.
            3. For each output multi-dimensional index:
                 a. Map it back to an index into `self`, treating any size-1
                    or padded dim of `self` as 0 in that position.
                 b. Same for `other`.
                 c. Sum the two scalar values into the output position.
            4. Return TinyArray(out_data, out_shape).
        """
        
        return self.__cross__(other, lambda a, b: a + b)

    def __mul__(self, other: "TinyArray") -> "TinyArray":
        """Element-wise multiply with broadcasting. Same logic as __add__,
        with multiplication instead of addition."""

        return self.__cross__(other, lambda a, b: a * b)



def broadcast_shapes(
    shape_a: tuple[int, ...],
    shape_b: tuple[int, ...],
) -> tuple[int, ...]:
    """Compute the output shape when broadcasting `shape_a` and `shape_b`.

    The rules (NumPy/PyTorch standard):

    1. Right-align the shapes (compare from the trailing dimension).
    2. Pad the shorter shape on the LEFT with 1s until they match in length.
    3. For each dimension, the two sizes must be equal, OR one of them must
       be 1. Otherwise raise ValueError.
    4. The output dimension is `max(a, b)` (with 1 acting as the smaller).

    Examples:
        broadcast_shapes((3,), (3,))         == (3,)
        broadcast_shapes((), (3, 4))         == (3, 4)
        broadcast_shapes((4,), (3, 4))       == (3, 4)
        broadcast_shapes((1, 4), (3, 4))     == (3, 4)
        broadcast_shapes((1, 4), (3, 1))     == (3, 4)
        broadcast_shapes((2, 3), (2, 4))     -> ValueError
        broadcast_shapes((3,), (4,))         -> ValueError

    Args:
        shape_a, shape_b: shape tuples (possibly empty for scalars).

    Returns:
        The broadcasted output shape as a tuple.

    Raises:
        ValueError: if the shapes are not broadcast-compatible.
    """

    reverse_output_shape: list[int] = []
    reverse_shape_a = shape_a[::-1]
    reverse_shape_b = shape_b[::-1]

    for i in range(max(len(shape_a), len(shape_b))):
        dim_a = reverse_shape_a[i] if i < len(shape_a) else 1
        dim_b = reverse_shape_b[i] if i < len(shape_b) else 1

        if dim_a == dim_b:
            reverse_output_shape.append(dim_a)
        elif dim_a == 1:
            reverse_output_shape.append(dim_b)
        elif dim_b == 1:
            reverse_output_shape.append(dim_a)
        else:
            raise ValueError(f"Shapes {shape_a} and {shape_b} are not broadcast-compatible")
    
    return tuple(reverse_output_shape[::-1])
