# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.tensors.matmul pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import numpy as np
import torch


def matmul_loops(A: list[list[float]], B: list[list[float]]) -> list[list[float]]:
    """Triple-nested-loop matmul. C = A @ B.

    Args:
        A: m×k matrix as a list of lists of floats.
        B: k×n matrix as a list of lists of floats.

    Returns:
        m×n matrix as a list of lists of floats.

    The shape rule: (m, k) @ (k, n) = (m, n). The inner dimensions must
    agree (assert this) and they collapse; the outer dims become the output.

    Each output entry:
        C[i][j] = sum over p in 0..k of A[i][p] * B[p][j]
    """
    C: list[list[float]] = []
    for i in range(len(A)):
        C.append([])
        for j in range(len(B[0])):
            C[i].append(0.0)
            for p in range(len(B)):
                C[i][j] += A[i][p] * B[p][j]
    return C


def matmul_numpy(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """NumPy matmul. C = A @ B.

    One line. Use the `@` operator or `np.matmul`. (`np.einsum("ij,jk->ik", A, B)`
    works too, and makes the dimension contraction explicit, but `@` is idiomatic.)
    """
    return A @ B


def matmul_torch(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor:
    """PyTorch matmul. C = A @ B. Output lives on the same device as the inputs.

    One line. Use `torch.matmul` or the `@` operator.
    """
    return torch.matmul(A, B)
