# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.tokenizer.bpe pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

from collections.abc import Callable
from os import PathLike
from time import perf_counter
from typing import Self

from g2c.tokenizer.bpe import BPETokenizer


class _BPETokenizerImpl:  # patched onto BPETokenizer by apply()
    @staticmethod
    def _get_pair_counts(
        ids: list[int],
        *,
        barrier_ids: set[int] | None = None,
    ) -> dict[tuple[int, int], int]:
        """Return the frequency of each adjacent pair in `ids`.

        Example:
            _get_pair_counts([1, 2, 1, 2, 3])
              -> {(1, 2): 2, (2, 1): 1, (2, 3): 1}

        Optional `barrier_ids` are excluded from pair counting. This is how
        reserved special tokens remain atomic during training.

        Hint: a single pass with a sliding window of size 2.
        """
        pair_counts = {}
        for i in range(len(ids) - 1):
            pair = (ids[i], ids[i + 1])
            if barrier_ids and (pair[0] in barrier_ids or pair[1] in barrier_ids):
                continue
            pair_counts[pair] = pair_counts.get(pair, 0) + 1
        return pair_counts

    @staticmethod
    def _merge(ids: list[int], pair: tuple[int, int], new_id: int) -> list[int]:
        """Replace every non-overlapping occurrence of `pair` in `ids` with `new_id`.

        Example:
            _merge([1, 2, 3, 1, 2], (1, 2), 99)  ->  [99, 3, 99]

        IMPORTANT — overlap rule (left-to-right greedy):
            _merge([1, 1, 1], (1, 1), 99)  ->  [99, 1]    (NOT [99, 99]; the
            second `1` is consumed by the first match, leaving only one `1` left.)

        Hint: scan with an explicit index `i`, advancing by 2 on a match
        and by 1 otherwise.
        """
        left, right = pair
        merged: list[int] = []
        append = merged.append

        i = 0
        n = len(ids)
        while i < n:
            if i + 1 < n and ids[i] == left and ids[i + 1] == right:
                append(new_id)
                i += 2
            else:
                append(ids[i])
                i += 1

        return merged

    def train_step(
        self,
        ids: list[int],
        new_id: int,
    ) -> tuple[list[int], tuple[int, int], int] | None:
        """Learn one BPE merge from the current token ID sequence.

        Algorithm:
          1. Count adjacent pair frequencies in `ids`.
          2. If no pairs remain, return None.
          3. Pick the most-frequent pair (ties broken arbitrarily — by
             insertion order in the dict, which is fine).
          4. Apply the merge to the ID list with `_merge`.
          5. Record the merge in `self.merges`.
          6. Record the new token bytes in `self.vocab`.

        Args:
            ids: current token ID sequence.
            new_id: ID to assign to the selected pair.

        Returns:
            `(updated_ids, merged_pair, merge_count)`, or None if there are no
            adjacent pairs left to merge.
        """
        pair_counts = self._get_pair_counts(ids, barrier_ids=self.special_token_ids)
        if not pair_counts:
            return None

        best_pair = max(pair_counts, key=pair_counts.get)
        best_pair_count = pair_counts[best_pair]

        self.merges[best_pair] = new_id
        self.vocab[new_id] = self.vocab[best_pair[0]] + self.vocab[best_pair[1]]

        return self._merge(ids, best_pair, new_id), best_pair, best_pair_count

    def encode(self, text: str) -> list[int]:
        """Encode `text` into a list of token IDs using the learned merges.

        Algorithm:
          1. Encode `text` to UTF-8 bytes → list of IDs (0–255).
          2. Repeatedly:
               a. Find all adjacent pairs in the current ID list.
               b. Among those that appear in `self.merges`, pick the one with
                  the LOWEST merge ID (i.e. the merge we learned earliest).
                  Earliest-learned merges have priority, just like in `train`.
               c. If no pair in the list is in `self.merges`, stop.
               d. Apply that merge to the ID list.
          3. Return the resulting list.

        Edge cases:
          - Empty `text` → empty list.
          - `text` containing characters never seen in training → still works,
            because every UTF-8 byte is in the base vocab.
        """
        ids = self._encode_initial_ids(text)

        while True:
            pairs = []
            for i in range(len(ids) - 1):
                pairs.append((ids[i], ids[i + 1]))
            merge_candidates = [pair for pair in pairs if pair in self.merges]

            if not merge_candidates:
                break

            best_pair = min(merge_candidates, key=lambda pair: self.merges[pair])
            ids = self._merge(ids, best_pair, self.merges[best_pair])

        return ids

    def decode(self, ids: list[int]) -> str:
        """Reverse of `encode`: reconstruct the original text from IDs.

        Algorithm:
          1. For each ID, look up its byte sequence in `self.vocab`.
          2. Concatenate them.
          3. Decode as UTF-8.

        Use `errors="replace"` on the UTF-8 decode to be safe against
        partial-byte ID sequences (would not arise from a correct round-trip,
        but is a robust default).

        Hint: a one-liner with `b"".join(...)` and `.decode("utf-8", errors="replace")`.
        """
        byte_text = b"".join(self.vocab[id] for id in ids)
        return byte_text.decode("utf-8", errors="replace")

