# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.rag.store pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import numpy as np
from .chunk import Chunk

from g2c.rag.store import NumpyVectorStore


class _NumpyVectorStoreImpl:  # patched onto NumpyVectorStore by apply()
    def search(
        self,
        query: np.ndarray,
        *,
        k: int = 5,
    ) -> list[tuple[Chunk, float]]:
        """Top-`k` cosine-similarity matches for `query`.

        Args:
            query: shape `(self.dim,)` 1-D array OR `(1, self.dim)`
                2-D. Either way, must be L2-normalized for cosine
                similarity to reduce to a dot product. The function
                squeezes 2-D `(1, dim)` inputs to 1-D as a convenience.
            k: number of results to return. Must be > 0. If the store
                has fewer than k chunks, returns all of them
                (sorted by similarity).

        Returns:
            A list of `(chunk, similarity)` tuples, ordered by
            similarity DESCENDING (most-similar first). Length is
            `min(k, len(self))`. Similarities are plain Python floats
            (not numpy scalars) — friendlier for JSON dumping.

        Raises:
            ValueError: on empty store, k <= 0, dim mismatch.

        Recipe:
            1. # Validate.
               if len(self) == 0:
                   raise ValueError("cannot search an empty store")
               if k <= 0:
                   raise ValueError(f"k must be > 0, got {k}")

            2. # Normalize input shape: accept (dim,) or (1, dim).
               if query.ndim == 2 and query.shape[0] == 1:
                   query = query[0]
               if query.ndim != 1:
                   raise ValueError(
                       f"query must be 1-D (dim,) or 2-D (1, dim); "
                       f"got shape {query.shape}"
                   )
               if query.shape[0] != self._dim:
                   raise ValueError(
                       f"query dim {query.shape[0]} != store dim {self._dim}"
                   )

            3. # Cosine = dot product (vectors are L2-normalized by
               # contract).
               sims = self._vectors @ query.astype(self._vectors.dtype)
               # sims shape: (len(self),)

            4. # Top-k. argpartition is O(N) for getting the top-k
               # unsorted; we then sort just those k for the final
               # ordering.
               k_eff = min(k, len(self))
               if k_eff == len(self):
                   top_idx = np.argsort(sims)[::-1]
               else:
                   # Partition so the top k are in the last k positions
                   # (no guaranteed order within), then sort those k.
                   part = np.argpartition(sims, -k_eff)[-k_eff:]
                   top_idx = part[np.argsort(sims[part])[::-1]]

            5. # Return as Python tuples for JSON-friendliness.
               return [
                   (self._chunks[int(i)], float(sims[int(i)]))
                   for i in top_idx
               ]

        Implementation notes:

          * The dot-product trick is correct ONLY when both query and
            stored vectors are L2-normalized. If a caller passes a
            raw, un-normalized query vector, the "similarities"
            returned are scaled by `||query||` — which doesn't change
            the argmax order (so the TOP-K is still right!) but does
            distort the actual similarity numbers. That's a subtle
            footgun: results LOOK ranked correctly, but the float
            scores are meaningless.

          * `argpartition` vs `argsort`: argpartition is `O(N)` for
            "get the top k indices unordered." For small k (< ~50)
            this is materially faster than sorting the whole array,
            which is `O(N log N)`. For large k (k ≥ N/2), sort is
            simpler and not slower. The branch in step 4 picks the
            right one.

          * `query.astype(self._vectors.dtype)` is cheap (no copy if
            dtypes already match) and avoids the silent f64↔f32
            promotion that would otherwise upcast `self._vectors`.

          * Returning Python floats (not numpy scalars) matters for
            anyone JSON-dumping results. `json` chokes on numpy
            scalar types; the explicit `float(...)` cast prevents
            "Object of type float32 is not JSON serializable."

        Sanity values:

          * Store with N chunks, k=N+1: returns N results (all of
            them) — does not pad with None / does not raise.

          * Store has the query vector itself (e.g. `add(c, query)`
            then `search(query)`): that chunk is the top result with
            similarity ≈ 1.0 (exactly 1.0 modulo float rounding).

          * Two identical chunks with identical vectors: both appear
            in the top-k with the same similarity; their relative
            order is implementation-defined.

          * k=1: returns the single best match.
        """
        if len(self) == 0:
            raise ValueError("cannot search an empty store")
        if k <= 0:
            raise ValueError(f"k must be > 0, got {k}")

        if query.ndim == 2 and query.shape[0] == 1:
            query = query[0]
        if query.ndim != 1:
            raise ValueError(
                "query must be 1-D (dim,) or 2-D (1, dim); "
                f"got shape {query.shape}"
            )
        if query.shape[0] != self._dim:
            raise ValueError(
                f"query dim {query.shape[0]} != store dim {self._dim}"
            )

        sims = self._vectors @ query.astype(self._vectors.dtype, copy=False)
        k_eff = min(k, len(self))
        if k_eff == len(self):
            top_idx = np.argsort(sims)[::-1]
        else:
            partitioned = np.argpartition(sims, -k_eff)[-k_eff:]
            top_idx = partitioned[np.argsort(sims[partitioned])[::-1]]

        return [
            (self._chunks[int(index)], float(sims[int(index)]))
            for index in top_idx
        ]

