# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.pretraining.trainer pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import time
from collections.abc import Callable
from os import PathLike
from pathlib import Path
import torch
from g2c.nn import SGD, Module, resolve_device
from g2c.training import AdamW, clip_grad_norm_, cosine_with_warmup
from .data import get_lm_batch
from .loss import lm_cross_entropy

from g2c.pretraining.trainer import Trainer


class _TrainerImpl:  # patched onto Trainer by apply()
    def train_step(self, train_ids: torch.Tensor) -> dict[str, float]:
        """Perform one training step on a fresh random batch.

        Args:
            train_ids: 1-D LongTensor of training token IDs.

        Returns:
            A dict of metrics for this step:
                'loss':       the scalar loss this step (Python float)
                'lr':         the lr applied this step (Python float)
                'grad_norm':  the pre-clip global grad norm if
                              `grad_clip` is set; else 0.0

        Recipe — exactly this order:

            1. # Sample a fresh batch of (input, target) windows.
               x, y = get_lm_batch(
                   train_ids,
                   self.batch_size,
                   self.context_length,
                   generator=self.generator,
               )
               x = x.to(self.device)
               y = y.to(self.device)

            2. # Pull the lr for THIS step (before incrementing the
               # counter) and write it onto the optimizer. The
               # schedule reads `self.step` directly via `self.lr()`.
               lr = self.lr()
               self.optimizer.lr = lr

            3. self.optimizer.zero_grad()

            4. logits = self.model(x)                # (B, T, V)

            5. loss = lm_cross_entropy(logits, y)    # scalar

            6. loss.backward()

            7. # Optional global gradient clipping.
               if self.grad_clip is not None:
                   grad_norm = clip_grad_norm_(
                       self.model.parameters(), self.grad_clip
                   )
               else:
                   grad_norm = 0.0

            8. self.optimizer.step()

            9. self.step += 1
               # Advanced AFTER the step so `self.lr()` and
               # `self.step` are consistent within a single step.

           10. return {
                   'loss': loss.item(),
                   'lr': lr,
                   'grad_norm': grad_norm,
               }

        Common reorderings to avoid:

          * **Stepping the counter before applying the optimizer.** The
            lr you computed was for step `self.step`, but you'd be
            applying it AFTER incrementing — your effective schedule is
            shifted by one.
          * **Clipping after `optimizer.step()`.** The gradients have
            already been consumed; clipping after is a no-op on this
            step and clips on the NEXT step's stale grads (assuming
            you don't zero_grad first, which you should).
          * **Forgetting `zero_grad`.** PyTorch's `.backward()`
            ACCUMULATES into `.grad`. Without `zero_grad`, this step's
            gradient is added to the previous step's, the optimizer
            sees a wildly large effective gradient, and training
            diverges immediately.
        """
        x, y = get_lm_batch(
            train_ids,
            self.batch_size,
            self.context_length,
            generator=self.generator,
        )
        x = x.to(self.device)
        y = y.to(self.device)

        lr = self.lr()
        self.optimizer.lr = lr
        self.optimizer.zero_grad()

        logits = self.model(x)
        loss = lm_cross_entropy(logits, y)
        loss.backward()

        if self.grad_clip is not None:
            grad_norm = clip_grad_norm_(
                self.model.parameters(), self.grad_clip
            )
        else:
            grad_norm = 0.0

        self.optimizer.step()
        self.step += 1

        return {
            "loss": loss.item(),
            "lr": lr,
            "grad_norm": grad_norm,
        }

