# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.transformer.block pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

from collections.abc import Iterable
import torch
from g2c.attention import MultiHeadAttention
from g2c.nn import Module
from .ffn import FeedForward
from .layer_norm import LayerNorm

from g2c.transformer.block import Block


class _BlockImpl:  # patched onto Block by apply()
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply one transformer block to `x`. Returns `(B, T, D)`.

        Args:
            x: tensor of shape `(batch, T, embedding_dim)`. The output of
                the previous block — or, for the first block, of the
                token + position embedding sum.

        Returns:
            Tensor of the same shape as `x`. The residual stream after
            both sublayers have written into it.

        Recipe (two lines, in this exact order):

            1. x = x + self.attn(self.ln1(x))
            2. x = x + self.ffn(self.ln2(x))
            3. return x

        Read the structure carefully:

          * `ln1(x)` normalizes the input BEFORE attention sees it.
            Attention writes its update into a normalized space.
          * `attn(ln1(x))` is the attention sublayer's contribution. It
            has the same shape as `x`.
          * `x + attn(ln1(x))` adds that contribution back into the
            residual stream. The unnormalized `x` keeps flowing forward,
            with the attention update added.
          * `ln2(x)` (where `x` is now the post-attn residual) normalizes
            again before the FFN sublayer.
          * `ffn(ln2(x))` is the FFN sublayer's contribution.
          * Final `x = x + ffn(...)` adds it back.

        Common confusions to avoid:

          * The residuals are NOT normalized. Only the sublayer INPUT is
            normalized; the residual `x` is added unmodified. This is
            what makes the residual stream a "highway" that gradients
            flow through cleanly.
          * The TWO LayerNorms are independent — `ln1` and `ln2` each
            have their own gamma/beta. They're not the same module
            applied twice.
          * The order is "norm, then sublayer, then add." Post-norm
            (the order in the original 2017 paper) is "sublayer, then
            add, then norm" and trains differently. See the lesson page
            for why pre-norm won.
        """
        x = x + self.attn(self.ln1(x))
        x = x + self.ffn(self.ln2(x))
        return x

