"""Runtime patcher: walk g2c/solutions/ and bind impls onto g2c/ targets.

Recipe-B convention: each mirror file may contain

  * `_<ClassName>Impl` holder classes whose methods are copied onto the
    same-named real class in the matching `g2c.<topic>.<file>` module.
  * Module-level functions (non-underscore-prefixed) which are copied
    onto the matching module as attributes of the same name.

`apply()` is idempotent: re-running it just re-binds the same impls.
"""
from __future__ import annotations

import importlib
import inspect
from pathlib import Path


_ROOT = Path(__file__).parent
_HOLDER_SUFFIX = "Impl"
# Class-attribute names auto-generated by Python that we never want to copy.
_HOLDER_SKIP = frozenset(
    {"__dict__", "__weakref__", "__doc__", "__module__", "__qualname__"}
)


def _iter_mirror_modules() -> list[str]:
    """Return dotted names of every mirror module under g2c.solutions."""
    out: list[str] = []
    for path in sorted(_ROOT.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        if path.name == "__init__.py" or path.name.startswith("_"):
            continue
        rel = path.relative_to(_ROOT).with_suffix("")
        out.append("g2c.solutions." + ".".join(rel.parts))
    return out


def _patch_one(mirror_name: str) -> list[str]:
    mirror = importlib.import_module(mirror_name)
    target_name = mirror_name.replace("g2c.solutions.", "g2c.", 1)
    target_module = importlib.import_module(target_name)
    swapped: list[str] = []

    # Holder classes -> class methods.
    for attr_name in dir(mirror):
        if not (attr_name.startswith("_") and attr_name.endswith(_HOLDER_SUFFIX)):
            continue
        holder = getattr(mirror, attr_name)
        if not inspect.isclass(holder) or holder.__module__ != mirror_name:
            continue
        target_class_name = attr_name[1 : -len(_HOLDER_SUFFIX)]
        target_class = getattr(target_module, target_class_name, None)
        if target_class is None or not inspect.isclass(target_class):
            continue
        for member_name, member in vars(holder).items():
            if member_name in _HOLDER_SKIP:
                continue
            setattr(target_class, member_name, member)
            swapped.append(f"{target_name}.{target_class_name}.{member_name}")

    # Free functions -> module attributes.
    for attr_name, attr in vars(mirror).items():
        if attr_name.startswith("_"):
            continue
        if not inspect.isfunction(attr):
            continue
        if attr.__module__ != mirror_name:
            continue
        setattr(target_module, attr_name, attr)
        swapped.append(f"{target_name}.{attr_name}")

    return swapped


def apply() -> list[str]:
    """Bind every mirror impl onto its scaffold target. Returns swapped qualnames."""
    swapped: list[str] = []
    for mirror_name in _iter_mirror_modules():
        swapped.extend(_patch_one(mirror_name))
    return swapped
