"""Runtime patcher: walk g2c/solutions/ and bind impls onto g2c/ targets.

Recipe-B convention: each mirror file may contain

  * `_<ClassName>Impl` holder classes whose methods are copied onto the
    same-named real class in the matching `g2c.<topic>.<file>` module.
  * Module-level functions (non-underscore-prefixed) which are copied
    onto the matching module as attributes of the same name.

`apply()` is idempotent: re-running it just re-binds the same impls.
"""
from __future__ import annotations

import importlib
import inspect
import types
from collections.abc import Callable, Iterable
from pathlib import Path

from ._selection import SelectionError, resolve

_ROOT = Path(__file__).parent
_HOLDER_SUFFIX = "Impl"
# Class-attribute names auto-generated by Python that we never want to copy.
_HOLDER_SKIP = frozenset(
    {"__dict__", "__weakref__", "__doc__", "__module__", "__qualname__"}
)


def _iter_mirror_modules() -> list[str]:
    """Return dotted names of every mirror module under g2c.solutions."""
    out: list[str] = []
    for path in sorted(_ROOT.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        if path.name == "__init__.py" or path.name.startswith("_"):
            continue
        rel = path.relative_to(_ROOT).with_suffix("")
        out.append("g2c.solutions." + ".".join(rel.parts))
    return out


def _rebind_globals(func: types.FunctionType, target_module) -> types.FunctionType:
    """Return a copy of `func` whose `__globals__` is the target module's namespace.

    Why: the mirror file imports only a narrow shim (e.g. the target class).
    Impl bodies often reference *other* names from the target module
    (sibling functions, module-level constants like XOR_DATA, the
    `random` module imported by the target file). If we leave the
    function bound to the mirror's globals, those references fail —
    AND in a subtler way, names captured at mirror-import time are
    snapshots of the OLD scaffold, so calls would still hit
    `raise NotImplementedError`.

    Rebinding to the target's `__dict__` ensures every free name inside
    the impl resolves against the same namespace it would have had on
    the solutions branch — the real `g2c.<topic>.<file>` module.

    Decorators are handled by recursion: if `func` is a wrapper (like
    the one `@torch.no_grad()` produces) closing over the un-decorated
    function, that inner function also gets its globals rebound.
    Without this, `@torch.no_grad()` calls would resolve sibling names
    against the mirror's narrow namespace — where they captured stale
    scaffold references.
    """
    new_closure = None
    if func.__closure__:
        rebound_cells = []
        for cell in func.__closure__:
            try:
                contents = cell.cell_contents
            except ValueError:
                rebound_cells.append(cell)
                continue
            if isinstance(contents, types.FunctionType):
                rebound_cells.append(
                    types.CellType(_rebind_globals(contents, target_module))
                )
            else:
                rebound_cells.append(cell)
        new_closure = tuple(rebound_cells)

    new_func = types.FunctionType(
        func.__code__,
        target_module.__dict__,
        func.__name__,
        func.__defaults__,
        new_closure,
    )
    new_func.__kwdefaults__ = func.__kwdefaults__
    new_func.__qualname__ = func.__qualname__
    new_func.__module__ = target_module.__name__
    # Only copy `__wrapped__` when the original actually has one. Setting it
    # to None unconditionally is not the same as leaving it absent:
    # `inspect.unwrap` follows the attribute and hands None to `getfile`,
    # so `inspect.getsource(...)` / `help(...)` raise TypeError on every
    # patched function — which a student in solutions mode hits the first
    # time they try to read an implementation they just enabled.
    if hasattr(func, "__wrapped__"):
        new_func.__wrapped__ = func.__wrapped__
    return new_func


def _rebind_super(func: types.FunctionType, target_class: type) -> types.FunctionType:
    """Rebind the `__class__` closure cell so bare `super()` finds target_class.

    Bare `super()` (with no args) compiles into a load of the implicit
    `__class__` cell that Python attaches to a method via its enclosing
    class. If we move the method to a *different* class, the cell still
    points at the holder class — and `super()` fails because `self` is
    not an instance of the holder.

    Fix: swap the cell to one referencing the real target class.
    """
    code = func.__code__
    if "__class__" not in code.co_freevars:
        return func
    idx = code.co_freevars.index("__class__")
    closure = list(func.__closure__) if func.__closure__ else [None] * len(code.co_freevars)
    closure[idx] = types.CellType(target_class)
    new_func = types.FunctionType(
        code,
        func.__globals__,
        func.__name__,
        func.__defaults__,
        tuple(closure),
    )
    new_func.__kwdefaults__ = func.__kwdefaults__
    new_func.__qualname__ = func.__qualname__
    new_func.__module__ = func.__module__
    return new_func


def _maybe_rebind(value, target_module, target_class=None):
    """Wrap classmethods/staticmethods so the wrapped function gets target globals.

    If `target_class` is given (method-on-class case), also rebind any
    bare `super()` reference to the target class.
    """
    def _wrap(func):
        rebound = _rebind_globals(func, target_module)
        if target_class is not None:
            rebound = _rebind_super(rebound, target_class)
        return rebound

    if isinstance(value, staticmethod):
        return staticmethod(_wrap(value.__func__))
    if isinstance(value, classmethod):
        return classmethod(_wrap(value.__func__))
    if isinstance(value, types.FunctionType):
        return _wrap(value)
    return value  # property, descriptor, slot, etc. — leave alone


def _patch_one(
    mirror_name: str,
    allow: Callable[[str], bool] | None = None,
) -> tuple[list[str], dict[int, object]]:
    """Patch a single mirror module's impls onto its scaffold target.

    `allow` optionally filters which members get bound, by member name. It is
    how a per-module selection keeps `TransformerLM.forward` (Module 09) and
    `TransformerLM.forward_cached` (Module 16) apart despite their sharing a
    class. `None` binds everything in the mirror.

    Returns (swapped_qualnames, rebindings) where `rebindings` maps the
    id() of each replaced free-function object to the new impl, so that
    `apply()` can rebind re-exports in parent packages.
    """
    mirror = importlib.import_module(mirror_name)
    target_name = mirror_name.replace("g2c.solutions.", "g2c.", 1)
    target_module = importlib.import_module(target_name)
    swapped: list[str] = []
    rebindings: dict[int, object] = {}

    # Holder classes -> class methods.
    #
    # Class re-exports are NOT a problem: `from .x import C` re-exports
    # the same class object whose `__dict__` we mutate, so method swaps
    # are visible everywhere automatically.
    for attr_name in dir(mirror):
        if not (attr_name.startswith("_") and attr_name.endswith(_HOLDER_SUFFIX)):
            continue
        holder = getattr(mirror, attr_name)
        if not inspect.isclass(holder) or holder.__module__ != mirror_name:
            continue
        target_class_name = attr_name[1 : -len(_HOLDER_SUFFIX)]
        target_class = getattr(target_module, target_class_name, None)
        if target_class is None or not inspect.isclass(target_class):
            continue
        for member_name, member in vars(holder).items():
            if member_name in _HOLDER_SKIP:
                continue
            if allow is not None and not allow(member_name):
                continue
            bound = _maybe_rebind(member, target_module, target_class)
            setattr(target_class, member_name, bound)
            swapped.append(f"{target_name}.{target_class_name}.{member_name}")

    # Free functions -> module attributes. Snapshot the old function so we
    # can find and rebind any `from .submodule import func` re-exports.
    for attr_name, attr in vars(mirror).items():
        if attr_name.startswith("_"):
            continue
        if not inspect.isfunction(attr):
            continue
        if attr.__module__ != mirror_name:
            continue
        if allow is not None and not allow(attr_name):
            continue
        old = getattr(target_module, attr_name, None)
        bound = _rebind_globals(attr, target_module)
        setattr(target_module, attr_name, bound)
        swapped.append(f"{target_name}.{attr_name}")
        if old is not None and old is not bound:
            rebindings[id(old)] = bound

    return swapped, rebindings


def _rebind_reexports(rebindings: dict[int, object]) -> list[str]:
    """Update every `from .x import func` re-export in already-loaded g2c modules."""
    import sys

    rebound: list[str] = []
    for mod_name, mod in list(sys.modules.items()):
        if mod is None or not mod_name.startswith("g2c"):
            continue
        if mod_name.startswith("g2c.solutions"):
            continue
        try:
            members = list(vars(mod).items())
        except TypeError:
            continue
        for attr_name, value in members:
            new = rebindings.get(id(value))
            if new is None:
                continue
            setattr(mod, attr_name, new)
            rebound.append(f"{mod_name}.{attr_name}")
    return rebound


def apply(only: Iterable[str] | None = None) -> list[str]:
    """Bind mirror impls onto their scaffold targets. Returns swapped qualnames.

    `only` selects which course modules to hand over. `None` (the default)
    binds everything, preserving the original behavior. Otherwise it is an
    iterable of selectors — module ids, ranges, topics, or mirror paths::

        apply()                          # every module
        apply(["01-07"])                 # Modules 01 through 07
        apply(["attention", "09b"])      # one topic plus one module

    Selecting a subset is the supported way to get unstuck without discarding
    your own work: hand back only the modules you're not debugging. See
    `_selection` for the full selector grammar.

    Raises `SelectionError` if a selector names nothing in the course — a
    silent no-op would leave a stuck student staring at the same failure.
    """
    if only is None:
        mirrors: dict[str, Callable[[str], bool] | None] = {
            name: None for name in _iter_mirror_modules()
        }
    else:
        resolved = resolve(only)
        _assert_mirrors_exist(resolved)
        mirrors = {
            name: (lambda member, ts=targets: any(t.allows(member) for t in ts))
            for name, targets in resolved.items()
        }

    swapped: list[str] = []
    rebindings: dict[int, object] = {}
    for mirror_name, allow in mirrors.items():
        s, r = _patch_one(mirror_name, allow)
        swapped.extend(s)
        rebindings.update(r)
    if rebindings:
        swapped.extend(_rebind_reexports(rebindings))
    return swapped


def _assert_mirrors_exist(resolved: dict[str, object]) -> None:
    """Fail loudly if the selection map names a mirror file that isn't there.

    The map in `_selection` is hand-maintained course metadata; a renamed or
    deleted mirror file would otherwise turn into a selection that silently
    binds less than the student asked for.
    """
    known = set(_iter_mirror_modules())
    missing = sorted(set(resolved) - known)
    if missing:
        raise SelectionError(
            "solutions selection map is stale — these mirror modules do not "
            f"exist: {', '.join(missing)}. Update g2c/solutions/_selection.py."
        )
