# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.embeddings.positional pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import math
from collections.abc import Iterable
import torch
from g2c.nn import Module

from g2c.embeddings.positional import LearnedPositionalEmbedding, SinusoidalPositionalEmbedding


class _LearnedPositionalEmbeddingImpl:  # patched onto LearnedPositionalEmbedding by apply()
    def forward(self, seq_len: int) -> torch.Tensor:
        """Return positional embeddings for positions 0..seq_len-1.

        Args:
            seq_len: length of the sequence (must be ≤ max_seq_len).

        Returns:
            (seq_len, embedding_dim) tensor — the first `seq_len` rows of
            the learned table. This will broadcast correctly when added to
            a (batch, seq_len, embedding_dim) tensor of token embeddings.

        Hint: a one-liner — slice the weight table.
        """
        if seq_len > self.max_seq_len:
            raise ValueError(f"seq_len {seq_len} exceeds max_seq_len {self.max_seq_len}")
        return self.weight[:seq_len]



class _SinusoidalPositionalEmbeddingImpl:  # patched onto SinusoidalPositionalEmbedding by apply()
    def __init__(self, max_seq_len: int, embedding_dim: int) -> None:
        super().__init__()
        if embedding_dim % 2 != 0:
            raise ValueError("embedding_dim must be even for sinusoidal encoding")
        self.max_seq_len = max_seq_len
        self.embedding_dim = embedding_dim

        # TODO: build the (max_seq_len, embedding_dim) sinusoidal table and
        # assign it to self.weight. The table should NOT require grad.
        #
        # Recipe:
        #   1. positions = arange(max_seq_len)                shape (max_seq_len,)
        #   2. i = arange(0, embedding_dim, 2)                shape (embedding_dim/2,)
        #      div_term = 1.0 / (10000 ** (i / embedding_dim))
        #   3. angles = positions[:, None] * div_term[None, :]   shape (max_seq_len, embedding_dim/2)
        #   4. weight = empty(max_seq_len, embedding_dim)
        #      weight[:, 0::2] = sin(angles)
        #      weight[:, 1::2] = cos(angles)
        #   5. self.weight = weight   (no requires_grad — fixed table)
        
        positions = torch.arange(max_seq_len)
        i = torch.arange(0, embedding_dim, 2)
        div_term = 1.0 / (10000 ** (i / embedding_dim))
        angles = positions[:, None] * div_term[None, :]
        weight = torch.empty(max_seq_len, embedding_dim)
        weight[:, 0::2] = angles.sin()
        weight[:, 1::2] = angles.cos()
        weight.requires_grad_(False)
        self.weight = weight

    def forward(self, seq_len: int) -> torch.Tensor:
        """Return positional encodings for positions 0..seq_len-1.

        Args:
            seq_len: length of the sequence (must be ≤ max_seq_len).

        Returns:
            (seq_len, embedding_dim) tensor.

        Hint: a one-liner — slice `self.weight`.
        """
        if seq_len > self.max_seq_len:
            raise ValueError(f"seq_len {seq_len} exceeds max_seq_len {self.max_seq_len}")
        return self.weight[:seq_len]

