# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.inference.local pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import time
from typing import Any
import torch
from g2c.sampling import generate
from .backend import Backend, BackendInfo, InferenceResult

from g2c.inference.local import LocalTransformerBackend


class _LocalTransformerBackendImpl:  # patched onto LocalTransformerBackend by apply()
    def complete(
        self,
        prompt: str,
        *,
        max_new_tokens: int = 128,
        temperature: float = 1.0,
        top_k: int | None = None,
        top_p: float | None = None,
    ) -> InferenceResult:
        """Encode → time → generate → slice → decode → return.

        Args:
            prompt: the input string. Non-empty after tokenization.
            max_new_tokens: forwarded to `g2c.sampling.generate`.
            temperature: forwarded.
            top_k: forwarded.
            top_p: forwarded.

        Returns:
            `InferenceResult` with:
              * prompt = the input string
              * completion = the decoded text of the NEW tokens (does
                not include the prompt)
              * prompt_tokens = number of tokens in the encoded prompt
              * completion_tokens = number of NEW tokens generated
                (not including the prompt)
              * latency_ms = wall-clock time around the generate call
              * backend = self.info
              * metadata = {"sampling": {...the four params...},
                            "eos_id": self._eos_id}

        Recipe:
            1. # Validate.
               if not isinstance(prompt, str):
                   raise TypeError(...)
               if max_new_tokens <= 0:
                   raise ValueError(...)

            2. # Encode.
               prompt_ids: list[int] = self._tokenizer.encode(prompt)
               if len(prompt_ids) == 0:
                   raise ValueError("prompt encoded to 0 tokens")

            3. # Move to the model's device. Same idiom as
               # continuation_logprob:
               device = next(iter(self._model.parameters())).device
               prompt_tensor = torch.tensor(
                   prompt_ids, dtype=torch.long, device=device
               )

            4. # Time the generate call. Use perf_counter — high-
               # resolution and monotonic. Don't use time.time() here.
               t0 = time.perf_counter()
               full = generate(
                   self._model,
                   prompt_tensor,
                   max_new_tokens=max_new_tokens,
                   temperature=temperature,
                   top_k=top_k,
                   top_p=top_p,
                   eos_id=self._eos_id,
               )
               t1 = time.perf_counter()
               latency_ms = (t1 - t0) * 1000.0

            5. # Slice the prompt off and decode the rest.
               # `full` is 1-D shape (T_prompt + n_new,).
               completion_ids = full[len(prompt_ids):].tolist()
               completion = self._tokenizer.decode(completion_ids)

            6. # Build and return the result.
               return InferenceResult(
                   prompt=prompt,
                   completion=completion,
                   prompt_tokens=len(prompt_ids),
                   completion_tokens=len(completion_ids),
                   latency_ms=latency_ms,
                   backend=self._info,
                   metadata={
                       "sampling": {
                           "max_new_tokens": max_new_tokens,
                           "temperature": temperature,
                           "top_k": top_k,
                           "top_p": top_p,
                       },
                       "eos_id": self._eos_id,
                   },
               )

        Implementation notes:

          * `time.perf_counter()` is the right call. It's high-
            resolution (sub-millisecond on macOS), monotonic (immune
            to wall-clock NTP adjustments), and the documented
            standard for benchmarking. `time.time()` is wall clock —
            wrong tool.

          * The `(t1 - t0) * 1000.0` conversion is in float
            milliseconds, matching `InferenceResult.latency_ms`.

          * `generate` is wrapped in `@torch.no_grad()` already
            (Module 11), so there's no need to add another
            `no_grad` here. The model gets called inside no_grad;
            no autograd graph is built.

          * If `len(prompt_ids) >= model.max_seq_len` the model has
            no positional capacity for new tokens. `generate`'s
            crop step handles this for the forward pass, but the
            FIRST sampled token has no positional signal beyond
            what fit in the crop window. For pedagogical safety,
            we don't reject — we let `generate` deal with it. In
            production you'd typically refuse, log, and ask the
            caller to truncate.

          * The `metadata` dict is intentionally rich — keeps the
            sampling settings with the result so a JSON dump tells
            you "what we sampled with" alongside "what we got."

        Sanity values:

          * Greedy (temperature=0) on a deterministic model: same
            prompt always produces the same completion. The
            `completion_tokens` count equals exactly `max_new_tokens`
            unless `eos_id` was emitted earlier.

          * `max_new_tokens=1` on any prompt: `completion_tokens`
            is exactly 1 (or 0 if EOS was the first sampled token).

          * Empty prompt: raises ValueError before forwarding.
        """
        if not isinstance(prompt, str):
            raise TypeError(f"prompt must be str, got {type(prompt).__name__}")
        if max_new_tokens <= 0:
            raise ValueError(
                f"max_new_tokens must be positive, got {max_new_tokens}"
            )

        prompt_ids = self._tokenizer.encode(prompt)
        if len(prompt_ids) == 0:
            raise ValueError("prompt encoded to 0 tokens")

        device = _model_device(self._model)
        prompt_tensor = torch.tensor(prompt_ids, dtype=torch.long, device=device)

        start = time.perf_counter()
        full = generate(
            self._model,
            prompt_tensor,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
            eos_id=self._eos_id,
        )
        latency_ms = (time.perf_counter() - start) * 1000.0

        completion_ids = [int(token_id) for token_id in full[len(prompt_ids) :].tolist()]
        completion = self._tokenizer.decode(completion_ids)
        return InferenceResult(
            prompt=prompt,
            completion=completion,
            prompt_tokens=len(prompt_ids),
            completion_tokens=len(completion_ids),
            latency_ms=latency_ms,
            backend=self._info,
            metadata={
                "sampling": {
                    "max_new_tokens": max_new_tokens,
                    "temperature": temperature,
                    "top_k": top_k,
                    "top_p": top_p,
                },
                "eos_id": self._eos_id,
            },
        )

