# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.inference.ollama pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import json
import time
import urllib.error
import urllib.request
from typing import Any
from uuid import uuid4
from .backend import Backend, BackendInfo, ChatResult, InferenceResult

from g2c.inference.ollama import OllamaBackend


class _OllamaBackendImpl:  # patched onto OllamaBackend by apply()
    def complete(
        self,
        prompt: str,
        *,
        max_new_tokens: int = 128,
        temperature: float = 1.0,
        top_k: int | None = None,
        top_p: float | None = None,
        think: bool | None = None,
    ) -> InferenceResult:
        """POST to `{base_url}/api/generate` and parse the response.

        Args:
            prompt: input string. Non-empty.
            max_new_tokens: forwarded as `options.num_predict`.
            temperature: forwarded as `options.temperature`.
            top_k: forwarded as `options.top_k` (omitted from the
                payload entirely if None — letting Ollama use its
                default rather than passing 0).
            top_p: forwarded as `options.top_p` (likewise).

        Returns:
            `InferenceResult` with:
              * prompt = the input string
              * completion = the response's `"response"` field
              * prompt_tokens = response's `"prompt_eval_count"`,
                or None if the server didn't return it
              * completion_tokens = response's `"eval_count"`, or None
              * latency_ms = wall-clock time around the HTTP call
              * backend = self.info
              * metadata = {
                    "server_total_duration_ms": <total_duration / 1e6>,
                    "server_eval_duration_ms":  <eval_duration / 1e6>,
                    "sampling": {... the four params ...},
                }
                (The server's reported timings are kept alongside
                wall-clock for benchmarking comparisons.)

        Raises:
            OllamaError: if Ollama isn't running, the HTTP call fails,
                the response isn't valid JSON, or the response is
                missing the `"response"` field. The chained `__cause__`
                is the underlying stdlib exception.

        Recipe:
            1. # Validate.
               if not isinstance(prompt, str) or len(prompt) == 0:
                   raise ValueError("prompt must be a non-empty str")
               if max_new_tokens <= 0:
                   raise ValueError("max_new_tokens must be > 0")

            2. # Build the request body. Only include sampling
               # options that were explicitly set — leaving an option
               # absent lets Ollama fill in its default.
               options: dict[str, Any] = {
                   "num_predict": int(max_new_tokens),
                   "temperature": float(temperature),
               }
               if top_k is not None:
                   options["top_k"] = int(top_k)
               if top_p is not None:
                   options["top_p"] = float(top_p)

               body = {
                   "model":   self._model_id,
                   "prompt":  prompt,
                   "stream":  False,
                   "options": options,
               }
               body_bytes = json.dumps(body).encode("utf-8")

            3. # Build the HTTP request.
               url = f"{self._base_url}/api/generate"
               req = urllib.request.Request(
                   url,
                   data=body_bytes,
                   headers={"Content-Type": "application/json"},
                   method="POST",
               )

            4. # Time + send. Wrap stdlib errors in OllamaError so
               # callers have one type to catch.
               t0 = time.perf_counter()
               try:
                   with self._urlopen(req, timeout=self._timeout) as resp:
                       resp_bytes = resp.read()
               except urllib.error.HTTPError as e:
                   raise OllamaError(
                       f"Ollama HTTP error {e.code} at {url}: {e.reason}"
                   ) from e
               except urllib.error.URLError as e:
                   raise OllamaError(
                       f"Could not reach Ollama at {url}: {e.reason}"
                   ) from e
               t1 = time.perf_counter()
               latency_ms = (t1 - t0) * 1000.0

            5. # Parse JSON.
               try:
                   data = json.loads(resp_bytes)
               except json.JSONDecodeError as e:
                   raise OllamaError(
                       f"Ollama returned non-JSON response from {url}"
                   ) from e
               if "response" not in data:
                   raise OllamaError(
                       f"Ollama response missing 'response' field: "
                       f"keys={list(data.keys())}"
                   )

            6. # Build result.
               total_dur_ns = data.get("total_duration")
               eval_dur_ns  = data.get("eval_duration")
               metadata = {
                   "sampling": {
                       "max_new_tokens": max_new_tokens,
                       "temperature":    temperature,
                       "top_k":          top_k,
                       "top_p":          top_p,
                   },
                   "server_total_duration_ms": (
                       float(total_dur_ns) / 1e6 if total_dur_ns is not None else None
                   ),
                   "server_eval_duration_ms": (
                       float(eval_dur_ns)  / 1e6 if eval_dur_ns  is not None else None
                   ),
               }
               return InferenceResult(
                   prompt=prompt,
                   completion=data["response"],
                   prompt_tokens=data.get("prompt_eval_count"),
                   completion_tokens=data.get("eval_count"),
                   latency_ms=latency_ms,
                   backend=self._info,
                   metadata=metadata,
               )

        Implementation notes:

          * `Content-Type: application/json` is required by Ollama;
            without it the server rejects the request with a 400.

          * `urllib.request.urlopen` raises `HTTPError` on non-2xx
            (a subclass of `URLError`), and `URLError` on network
            failure. We translate both to `OllamaError` so callers
            don't need to care about stdlib exception hierarchy.

          * Ollama's `total_duration` is in NANOSECONDS. The conversion
            to milliseconds is `/ 1e6`. (Off-by-1000 here means
            "this 7B model takes 12000 ms = 12 s" when it actually
            took 12 ms — silently absurd.)

          * The wall-clock `latency_ms` and the server's
            `total_duration_ms` typically agree to within a few ms.
            They diverge if the network is slow or the server is
            warming up the model from disk. Track both — wall-clock
            is what the user feels; server-reported is what the
            model actually spent.

          * `eval_count` is the OUTPUT token count, NOT the input.
            The input token count is `prompt_eval_count`. Misnamed
            in the API but that's the spec.

        Sanity values:

          * Ollama not running: raises OllamaError with "Could not
            reach Ollama at ...". A fast failure mode.

          * Pulled model + valid prompt + Ollama running: returns
            an InferenceResult with non-empty completion, prompt
            and completion token counts, and latency on the order
            of seconds for a 7B model.

          * `max_new_tokens=1`: completion is a short string,
            completion_tokens is exactly 1.
        """
        if not isinstance(prompt, str) or len(prompt) == 0:
            raise ValueError("prompt must be a non-empty str")
        if max_new_tokens <= 0:
            raise ValueError(
                f"max_new_tokens must be positive, got {max_new_tokens}"
            )

        options: dict[str, Any] = {
            "num_predict": int(max_new_tokens),
            "temperature": float(temperature),
        }
        if top_k is not None:
            options["top_k"] = int(top_k)
        if top_p is not None:
            options["top_p"] = float(top_p)

        body: dict[str, Any] = {
            "model": self._model_id,
            "prompt": prompt,
            "stream": False,
            "options": options,
        }
        if think is not None:
            body["think"] = bool(think)
        url = f"{self._base_url}/api/generate"
        request = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        start = time.perf_counter()
        try:
            with self._urlopen(request, timeout=self._timeout) as response:
                response_bytes = response.read()
        except urllib.error.HTTPError as exc:
            raise OllamaError(
                f"Ollama HTTP error {exc.code} at {url}: {exc.reason}"
            ) from exc
        except urllib.error.URLError as exc:
            raise OllamaError(f"Could not reach Ollama at {url}: {exc.reason}") from exc
        latency_ms = (time.perf_counter() - start) * 1000.0

        try:
            data = json.loads(response_bytes)
        except json.JSONDecodeError as exc:
            raise OllamaError(f"Ollama returned non-JSON response from {url}") from exc

        if "response" not in data:
            raise OllamaError(
                "Ollama response missing 'response' field: "
                f"keys={list(data.keys())}"
            )

        total_duration = data.get("total_duration")
        eval_duration = data.get("eval_duration")
        return InferenceResult(
            prompt=prompt,
            completion=data["response"],
            prompt_tokens=data.get("prompt_eval_count"),
            completion_tokens=data.get("eval_count"),
            latency_ms=latency_ms,
            backend=self._info,
            metadata={
                "sampling": {
                    "max_new_tokens": max_new_tokens,
                    "temperature": temperature,
                    "top_k": top_k,
                    "top_p": top_p,
                },
                "server_total_duration_ms": (
                    float(total_duration) / 1e6 if total_duration is not None else None
                ),
                "server_eval_duration_ms": (
                    float(eval_duration) / 1e6 if eval_duration is not None else None
                ),
            },
        )

