# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.tools.builtins pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import ast
import operator
import os
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any
from .base import Tool, ToolError


def calculator_evaluate(expression: str) -> float:
    """Evaluate an arithmetic expression safely.

    Allowed: number constants, `+ - * / % ** //`, parentheses,
    unary `+` and `-`. Anything else — names, calls, subscripts,
    attribute access, comparisons, comprehensions — raises
    `ToolError`.

    The safety mechanism is structural, not blacklist-based: we parse
    to an AST, walk the tree, and explicitly check that every node is
    a member of a small allowed set. A node we don't recognize gets
    rejected. This is the right way to do "safe eval" — `eval()` with
    cleaned-up globals is famously not safe.

    Args:
        expression: the arithmetic expression as a string. Anything
            Python's parser accepts as an expression — but only the
            arithmetic subset will pass the structural check.

    Returns:
        The numeric result. `int` if the operations preserve int;
        `float` if any division / float constants get involved.

    Raises:
        ToolError: parse failures, disallowed AST nodes, or
            disallowed operators. The error message names the
            offending node type so the student can debug.

    Recipe:

        1. # Parse in expression mode. SyntaxError → ToolError.
           try:
               tree = ast.parse(expression, mode="eval")
           except SyntaxError as e:
               raise ToolError(f"could not parse: {e.msg}") from e

        2. # Walk the tree starting at the body (Expression's child).
           return _eval_node(tree.body)

        # And then a recursive helper that handles each allowed node:

        3. def _eval_node(node):
               # Constant: must be int or float, not str/None/bool.
               if isinstance(node, ast.Constant):
                   if isinstance(node.value, bool):
                       raise ToolError("booleans are not allowed in expressions")
                   if isinstance(node.value, (int, float)):
                       return node.value
                   raise ToolError(f"constant must be a number, got {type(node.value).__name__}")

               # BinOp: <op> must be in _BINOPS.
               if isinstance(node, ast.BinOp):
                   op = _BINOPS.get(type(node.op))
                   if op is None:
                       raise ToolError(f"binary operator not allowed: {type(node.op).__name__}")
                   return op(_eval_node(node.left), _eval_node(node.right))

               # UnaryOp: <op> must be in _UNARYOPS.
               if isinstance(node, ast.UnaryOp):
                   op = _UNARYOPS.get(type(node.op))
                   if op is None:
                       raise ToolError(f"unary operator not allowed: {type(node.op).__name__}")
                   return op(_eval_node(node.operand))

               # Anything else: reject by class name.
               raise ToolError(f"AST node not allowed: {type(node).__name__}")

    Implementation notes:

      * **Why structural, not regex/blacklist.** `re.search(r"[a-z]")`
        as a "safety check" misses Unicode names, `__import__`,
        `().__class__.__base__.__subclasses__()`, and a hundred other
        attack patterns documented in the safe-eval literature. AST
        whitelisting refuses everything not explicitly allowed, which
        is the only correct posture for executing untrusted input.

      * **Why reject booleans.** `True + 1` is `2` in Python because
        `bool` is a subclass of `int`. If the model emits
        `"true + 1"` (lowercase, syntax error), we reject at parse.
        If it emits `"True + 1"`, the constant *is* a bool — we
        reject explicitly so the model gets clear feedback.

      * **Pow gotcha.** `2 ** 1000000000` is parseable, allowed by
        the AST walker, and computes a giant integer that may take
        seconds to materialize. We don't guard against this — it's
        a known limitation. A production safe-eval would put a
        wall-clock timeout around the whole call. We don't because
        the pedagogical lesson is the AST walking, not denial-of-
        service mitigation.

      * **Recursive vs iterative walking.** The recipe uses recursion
        for clarity. For arbitrary-depth expressions you could blow
        the Python stack, but a 1000-deep parenthesized expression
        is not a real input we expect from the model. If you ever
        want a robust version, `ast.NodeVisitor` is the iterative
        approach.

    Sanity values:

      * `calculator_evaluate("1 + 2")` → 3
      * `calculator_evaluate("(2 + 3) * 4")` → 20
      * `calculator_evaluate("2 ** 10")` → 1024
      * `calculator_evaluate("-5 + 3")` → -2
      * `calculator_evaluate("7 / 2")` → 3.5
      * `calculator_evaluate("7 // 2")` → 3
      * `calculator_evaluate("'hello'")` → ToolError (string constant)
      * `calculator_evaluate("os.system('ls')")` → ToolError (Call/Name)
      * `calculator_evaluate("__import__('os')")` → ToolError (Name)
      * `calculator_evaluate("True + 1")` → ToolError (bool)
    """
    if not isinstance(expression, str):
        raise ToolError(
            f"expression must be a str, got {type(expression).__name__}"
        )

    try:
        tree = ast.parse(expression, mode="eval")
    except SyntaxError as exc:
        raise ToolError(f"could not parse: {exc.msg}") from exc

    def _eval_node(node: ast.AST):
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                raise ToolError("booleans are not allowed in expressions")
            if isinstance(node.value, (int, float)):
                return node.value
            raise ToolError(
                "constant must be a number, "
                f"got {type(node.value).__name__}"
            )

        if isinstance(node, ast.BinOp):
            op = _BINOPS.get(type(node.op))
            if op is None:
                raise ToolError(
                    f"binary operator not allowed: {type(node.op).__name__}"
                )
            return op(_eval_node(node.left), _eval_node(node.right))

        if isinstance(node, ast.UnaryOp):
            op = _UNARYOPS.get(type(node.op))
            if op is None:
                raise ToolError(
                    f"unary operator not allowed: {type(node.op).__name__}"
                )
            return op(_eval_node(node.operand))

        raise ToolError(f"AST node not allowed: {type(node).__name__}")

    return _eval_node(tree.body)
