# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.tools.loop pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import json
from typing import Any
from uuid import uuid4
from g2c.inference import Backend
from .base import (
    Tool,
    ToolCall,
    ToolError,
    ToolResult,
    ToolRunResult,
    ToolStep,  # noqa: F401 (used by run_with_tools scaffold)
)
from .parser import (  # noqa: F401 (used by run_with_tools scaffold)
    format_tool_results,
    parse_tool_calls,
)
from .registry import ToolRegistry
from .schema import (  # noqa: F401 (used by run_with_tools scaffold)
    DEFAULT_SYSTEM,
    NATIVE_DEFAULT_SYSTEM,
    render_tools_for_ollama,
    render_tools_for_prompt,
)


def run_with_tools(
    backend: Backend,
    registry: ToolRegistry,
    user_message: str,
    *,
    system: str | None = None,
    max_steps: int = 5,
    max_new_tokens: int = 1024,
    temperature: float = 0.2,
    top_k: int | None = None,
    top_p: float | None = None,
    use_native_tools: bool | None = None,
    think: bool | None = None,
) -> ToolRunResult:
    """Run the call → parse → dispatch → feedback loop until the model
    stops calling tools (or `max_steps` is hit).

    Args:
        backend: an inference `Backend` from Module 16.
        registry: the `ToolRegistry` describing available tools.
        user_message: the user's question / instruction. Non-empty.
        system: the leading system prompt. Defaults to `DEFAULT_SYSTEM`,
            which describes the tool-call format.
        max_steps: cap on the number of complete-parse-dispatch
            iterations. Each step is one backend call. Defaults to 5
            — enough for "fetch + transform + answer," not enough for
            an agent to hang in a loop.
        max_new_tokens: forwarded to `backend.complete`.
        temperature: forwarded. Default 0.2 — tool-using models work
            best near-greedy because tool selection benefits from
            consistency.
        top_k, top_p: forwarded.

    Returns:
        `ToolRunResult` with `final_answer`, `steps`, and
        `stopped_reason` filled in.

    Recipe:

        1. # Validate inputs.
           if not isinstance(user_message, str) or not user_message:
               raise ValueError("user_message must be a non-empty str")
           if max_steps <= 0:
               raise ValueError(f"max_steps must be > 0, got {max_steps}")

        2. # Build the initial transcript.
           tools_block = render_tools_for_prompt(registry.tools)
           transcript = "\n\n".join([
               system,
               tools_block,
               f"User: {user_message}",
               "Assistant:",
           ])

        3. # Loop. At each step: complete, parse, dispatch, append.
           steps: list[ToolStep] = []
           final_answer: str | None = None
           stopped_reason = "max_steps"

           for _ in range(max_steps):
               inference = backend.complete(
                   transcript,
                   max_new_tokens=max_new_tokens,
                   temperature=temperature,
                   top_k=top_k,
                   top_p=top_p,
               )
               completion = inference.completion
               tool_calls = parse_tool_calls(completion)

        4. #     No tool calls → this is the final answer.
               if not tool_calls:
                   final_answer = completion
                   steps.append(ToolStep(
                       completion=completion,
                       tool_calls=[],
                       tool_results=[],
                       inference=inference,
                   ))
                   stopped_reason = "no_more_calls"
                   break

        5. #     Dispatch each call; record the step.
               results = [dispatch_tool_call(registry, c) for c in tool_calls]
               steps.append(ToolStep(
                   completion=completion,
                   tool_calls=tool_calls,
                   tool_results=results,
                   inference=inference,
               ))

        6. #     Append the assistant's tool-calling output and the
               #     formatted results to the transcript, prompting
               #     for the next assistant turn.
               transcript = (
                   transcript
                   + " "
                   + completion
                   + "\n\n"
                   + format_tool_results(results)
                   + "\n\nAssistant:"
               )

        7. # Build and return the final result.
           return ToolRunResult(
               user_message=user_message,
               final_answer=final_answer,
               steps=steps,
               stopped_reason=stopped_reason,
               metadata={
                   "n_steps": len(steps),
                   "n_tool_calls": sum(len(s.tool_calls) for s in steps),
                   "tools_available": registry.names(),
                   "backend_name": backend.info.name,
                   "backend_model_id": backend.info.model_id,
               },
           )

    Implementation notes:

      * **Why not a full ReAct loop here?** ReAct interleaves
        "Thought / Action / Observation" turns and trains the model
        to plan explicitly. Module 19 builds that. Module 18's loop
        is purposely minimal: we trust the model to use tools when
        it needs to and to stop when it has the answer. The "no tool
        calls = done" exit condition is the simplest contract that
        works.

      * **Why the transcript grows monotonically.** Each step appends
        the assistant's last completion + the tool results. The
        prompt grows; the model reads its own past actions. This is
        a tiny conversation, not a true chat template — for a real
        chat-template-aware loop, you'd wrap each turn in
        `<|user|>...<|assistant|>...` markers per the model's
        instruction-tuning.

      * **What `stopped_reason="max_steps"` looks like.** The loop
        ran out without the model emitting a final answer. The last
        step's `completion` is the model's last tool-calling output;
        `final_answer` is None. This is the "the model is stuck in
        a loop" mode — Module 19's agent has more sophisticated stop
        criteria, but for now `max_steps` is the safety net.

      * **Why not stream tokens?** Streaming a tool-calling loop
        requires server-sent events, partial-JSON parsing, and a
        much bigger interface. We do the synchronous version. Real
        production tool-calling streams; the conceptual shape is the
        same.

    Sanity values:

      * Backend that always emits `"the answer is 42"` (no tool
        calls) → `final_answer="the answer is 42"`, one step,
        `stopped_reason="no_more_calls"`.

      * Backend that emits `<tool_call>{...calculator...}</tool_call>`
        on step 1 and `"the result is 4"` on step 2 → two steps,
        first step has tool_calls + tool_results, second step has
        the final answer.

      * Backend that always emits a tool call and `max_steps=2` →
        two steps, `final_answer=None`, `stopped_reason="max_steps"`.
    """
    if not isinstance(user_message, str) or not user_message:
        raise ValueError("user_message must be a non-empty str")
    if max_steps <= 0:
        raise ValueError(f"max_steps must be > 0, got {max_steps}")

    # Native path is opt-in by default-detection: if the user didn't say,
    # use it whenever the backend exposes chat_with_tools.
    if use_native_tools is None:
        use_native_tools = backend_supports_native_tools(backend)
    if use_native_tools and not backend_supports_native_tools(backend):
        raise ValueError(
            f"use_native_tools=True but backend {type(backend).__name__} "
            "has no chat_with_tools method"
        )

    # Default the system prompt to the channel-appropriate one. The
    # text-format channel needs the model to be told about <tool_call>
    # blocks; the native channel actively does not — the chat template
    # handles the format and the model has been post-trained for it.
    if system is None:
        system = NATIVE_DEFAULT_SYSTEM if use_native_tools else DEFAULT_SYSTEM

    if use_native_tools:
        return _run_with_native_tools(
            backend=backend,
            registry=registry,
            user_message=user_message,
            system=system,
            max_steps=max_steps,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
            think=think,
        )

    tools_block = render_tools_for_prompt(registry.tools)
    transcript = "\n\n".join(
        [
            system,
            tools_block,
            f"User: {user_message}",
            "Assistant:",
        ]
    )

    steps: list[ToolStep] = []
    final_answer: str | None = None
    stopped_reason = "max_steps"

    for _ in range(max_steps):
        inference = backend.complete(
            transcript,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
        )
        completion = inference.completion
        tool_calls = parse_tool_calls(completion)

        if not tool_calls:
            final_answer = completion
            steps.append(
                ToolStep(
                    completion=completion,
                    tool_calls=[],
                    tool_results=[],
                    inference=inference,
                )
            )
            stopped_reason = "no_more_calls"
            break

        tool_results = [dispatch_tool_call(registry, call) for call in tool_calls]
        steps.append(
            ToolStep(
                completion=completion,
                tool_calls=tool_calls,
                tool_results=tool_results,
                inference=inference,
            )
        )
        transcript = (
            transcript
            + " "
            + completion
            + "\n\n"
            + format_tool_results(tool_results)
            + "\n\nAssistant:"
        )

    return ToolRunResult(
        user_message=user_message,
        final_answer=final_answer,
        steps=steps,
        stopped_reason=stopped_reason,
        metadata={
            "n_steps": len(steps),
            "n_tool_calls": sum(len(step.tool_calls) for step in steps),
            "tools_available": registry.names(),
            "backend_name": backend.info.name,
            "backend_model_id": backend.info.model_id,
            "channel": "text-format",
        },
    )
