# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.sft.trainer pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import torch
from g2c.nn import Module, resolve_device
from g2c.training import AdamW, clip_grad_norm_, cosine_with_warmup
from .data import SFTExample, pad_and_collate
from .loss import masked_cross_entropy

from g2c.sft.trainer import SFTTrainer


class _SFTTrainerImpl:  # patched onto SFTTrainer by apply()
    def train_step(self) -> dict[str, float]:
        """Perform one SFT step on a fresh random batch.

        Returns:
            A dict of metrics for this step:
                'loss':       scalar loss (Python float)
                'lr':         lr applied this step (Python float)
                'grad_norm':  pre-clip global grad norm if grad_clip
                              is set; else 0.0

        Recipe — same shape as Module 10's `Trainer.train_step`, with
        the SFT data path and masked loss substituted in:

            1. # Sample a fresh batch from self.examples.
               x, y, loss_mask = self._sample_batch(self.examples)
               x = x.to(self.device)
               y = y.to(self.device)
               loss_mask = loss_mask.to(self.device)

            2. # LR for THIS step (before incrementing the counter).
               lr = self.lr()
               self.optimizer.lr = lr

            3. self.optimizer.zero_grad()

            4. logits = self.model(x)                 # (B, T-1, V)

            5. loss = masked_cross_entropy(
                   logits, y, loss_mask
               )                                       # scalar

            6. loss.backward()

            7. # Optional global gradient clipping.
               if self.grad_clip is not None:
                   grad_norm = clip_grad_norm_(
                       self.model.parameters(), self.grad_clip
                   )
               else:
                   grad_norm = 0.0

            8. self.optimizer.step()

            9. self.step += 1

           10. return {'loss': loss.item(), 'lr': lr,
                       'grad_norm': grad_norm}

        Common reorderings to avoid (same as Module 10):

          * Stepping the counter before applying the optimizer (lr
            schedule shifts by one).
          * Clipping after `optimizer.step()` (gradients already
            consumed; clipping is a no-op).
          * Forgetting `zero_grad` (PyTorch accumulates into .grad).
        """
        x, y, loss_mask = self._sample_batch(self.examples)
        x = x.to(self.device)
        y = y.to(self.device)
        loss_mask = loss_mask.to(self.device)

        lr = self.lr()
        self.optimizer.lr = lr

        self.optimizer.zero_grad()

        logits = self.model(x)

        loss = masked_cross_entropy(logits, y, loss_mask)

        loss.backward()

        if self.grad_clip is not None:
            grad_norm = clip_grad_norm_(self.model.parameters(), self.grad_clip)
        else:
            grad_norm = 0.0

        self.optimizer.step()

        self.step += 1

        return {"loss": loss.item(), "lr": lr, "grad_norm": grad_norm}

