# AUTO-GENERATED by scripts/build_solutions_mirror.py — do not edit by hand.
# Regenerate after updating the solutions branch:
#     source .venv/bin/activate && python scripts/build_solutions_mirror.py
"""Solutions for g2c.attention.multi_head pedagogical scaffolds.

Patched onto the scaffold targets by g2c.solutions.apply().
"""
from __future__ import annotations

import math
from collections.abc import Iterable
import torch
from g2c.nn import Linear, Module

from g2c.attention.multi_head import MultiHeadAttention


class _MultiHeadAttentionImpl:  # patched onto MultiHeadAttention by apply()
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply multi-head self-attention. Returns `(B, T, D)`.

        Args:
            x: tensor of shape `(batch, T, embedding_dim)`.

        Returns:
            Tensor of shape `(batch, T, embedding_dim)`. For each
            position `t`, the value is the concatenation of `H`
            independent weighted mixtures of value vectors — each
            mixture computed in its own `head_dim`-dimensional subspace
            — followed by a final output projection.

        Recipe:
            1. Project to Q, K, V:
                   q = self.q_proj(x)            # (B, T, D)
                   k = self.k_proj(x)            # (B, T, D)
                   v = self.v_proj(x)            # (B, T, D)

            2. Reshape into per-head form:
                   B, T, _ = x.shape
                   H, d_h = self.num_heads, self.head_dim
                   q = q.view(B, T, H, d_h).transpose(1, 2)  # (B, H, T, d_h)
                   k = k.view(B, T, H, d_h).transpose(1, 2)
                   v = v.view(B, T, H, d_h).transpose(1, 2)

               The view splits the last dim D into H slots of size d_h.
               The transpose makes H the leading batch-like dim so the
               next matmul applies independently to each head.

            3. Scaled dot-product scores (per head, in parallel):
                   scores = q @ k.transpose(-2, -1) / sqrt(d_h)
                                                    # (B, H, T, T)

               Note: scaling is by sqrt(d_h), NOT sqrt(D). Each dot
               product is over a d_h-dimensional subspace. Using sqrt(D)
               here over-scales the scores by sqrt(H), saturating the
               softmax in the wrong direction — a frequent multi-head
               bug.

            4. Apply the causal mask if self.causal:
                   mask = self.causal_mask(T, device=scores.device)
                   scores = scores.masked_fill(mask, float("-inf"))

               The (T, T) mask broadcasts over the (B, H, ., .) dims —
               the same positions are blocked in every head.

            5. Convert scores to attention weights:
                   weights = scores.softmax(dim=-1)   # (B, H, T, T)

            6. Mix the value vectors PER HEAD:
                   mixed = weights @ v                # (B, H, T, d_h)

            7. Concatenate heads back into a single (B, T, D) tensor:
                   mixed = mixed.transpose(1, 2).contiguous().view(B, T, D)

               Transpose moves H back next to d_h so the view can
               flatten the last two dims into D = H * d_h. The
               `.contiguous()` is required because `transpose` returns
               a non-contiguous view that `.view()` cannot reshape
               directly.

            8. Output projection:
                   return self.out_proj(mixed)        # (B, T, D)
        """
        q = self.q_proj(x)  # (B, T, D)
        k = self.k_proj(x)  # (B, T, D)
        v = self.v_proj(x)  # (B, T, D)

        B, T, _ = x.shape
        H, d_h = self.num_heads, self.head_dim

        q = q.view(B, T, H, d_h).transpose(1, 2)  # (B, H, T, d_h)
        k = k.view(B, T, H, d_h).transpose(1, 2)
        v = v.view(B, T, H, d_h).transpose(1, 2)

        scores = q @ k.transpose(-2, -1) / math.sqrt(d_h)  # (B, H, T, T)

        if self.causal:
            mask = self.causal_mask(T, device=scores.device)
            scores = scores.masked_fill(mask, float("-inf"))

        weights = scores.softmax(dim=-1)  # (B, H, T, T)
        mixed = weights @ v  # (B, H, T, d_h)
        mixed = mixed.transpose(1, 2).contiguous().view(B, T, self.embedding_dim)  # (B, T, D)

        return self.out_proj(mixed)  # (B, T, D)

    def attention_weights(self, x: torch.Tensor) -> torch.Tensor:
        """Return the per-head attention weight matrices for visualization.

        Args:
            x: tensor of shape `(batch, T, embedding_dim)`.

        Returns:
            Tensor of shape `(batch, H, T, T)`. Entry `[b, h, i, j]` is
            the attention weight from query position `i` to key position
            `j` in batch element `b`, head `h`. Each `[b, h, i, :]` row
            sums to 1.

        This is steps 1-5 of `forward` — Q/K projection, reshape, scaled
        dot product, mask, softmax — without value mixing or the output
        projection. It exists so exercise 4 (per-head visualization) has
        a clean public method to call.

        Recipe:
            1. q = self.q_proj(x)
            2. k = self.k_proj(x)
            3. reshape both into (B, H, T, d_h)
            4. scores = q @ k.transpose(-2, -1) / sqrt(d_h)
            5. apply causal mask if self.causal
            6. return scores.softmax(dim=-1)
        """
        q = self.q_proj(x)
        k = self.k_proj(x)

        B, T, _ = x.shape
        H, d_h = self.num_heads, self.head_dim

        q = q.view(B, T, H, d_h).transpose(1, 2)  # (B, H, T, d_h)
        k = k.view(B, T, H, d_h).transpose(1, 2)

        scores = q @ k.transpose(-2, -1) / math.sqrt(d_h)  # (B, H, T, T)

        if self.causal:
            mask = self.causal_mask(T, device=scores.device)
            scores = scores.masked_fill(mask, float("-inf"))

        return scores.softmax(dim=-1)  # (B, H, T, T)

